#!/usr/bin/env bash

set -e

echo "== create table via cloudformation"

STACK_NAME="cfn-dynamodb"

#"$(dirname "$0") is used to allow run scrip in any relative path

aws cloudformation deploy \
--template-file "$(dirname "$0")/create_table.yaml" \
--stack-name $STACK_NAME

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

aws dynamodb batch-write-item \
    --request-items file://$SCRIPT_DIR/request-items.json  \
    --return-consumed-capacity INDEXES \
    --return-item-collection-metrics SIZE