#!/bin/bash

set -e

PATH_PART=$1

LAMBDA_FUNCTION_NAME=$2

LAMBDA_FUNCTION_ID=$(aws apigateway get-rest-apis --query "items[?name=='$LAMBDA_FUNCTION_NAME'].id" --output text)

# remove the path /
PARENT_ID=$(aws apigateway get-resources --rest-api-id $LAMBDA_FUNCTION_ID --query "items[?path=='/'].id" --output text)

# Create resource
aws apigateway create-resource \
    --rest-api-id $LAMBDA_FUNCTION_ID \
    --parent-id $PARENT_ID \
    --path-part $PATH_PART